-- MySQL Script generated by MySQL Workbench
-- Mon Oct 10 10:27:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUMNO` (
  `Cod_Matrícula` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `DNI` VARCHAR(9) NULL,
  `FechaNacimiento` DATE NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Matrícula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSO` (
  `Cod_Curso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ALUMNO_Cod_Matrícula` INT NOT NULL,
  PRIMARY KEY (`Cod_Curso`, `ALUMNO_Cod_Matrícula`),
  INDEX `fk_CURSO_ALUMNO_idx` (`ALUMNO_Cod_Matrícula` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_ALUMNO`
    FOREIGN KEY (`ALUMNO_Cod_Matrícula`)
    REFERENCES `mydb`.`ALUMNO` (`Cod_Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESOR` (
  `Id_Profesor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Especialidad` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `CURSO_Cod_Curso` INT NOT NULL,
  `CURSO_ALUMNO_Cod_Matrícula` INT NOT NULL,
  PRIMARY KEY (`Id_Profesor`, `CURSO_Cod_Curso`, `CURSO_ALUMNO_Cod_Matrícula`),
  INDEX `fk_PROFESOR_CURSO1_idx` (`CURSO_Cod_Curso` ASC, `CURSO_ALUMNO_Cod_Matrícula` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_CURSO1`
    FOREIGN KEY (`CURSO_Cod_Curso` , `CURSO_ALUMNO_Cod_Matrícula`)
    REFERENCES `mydb`.`CURSO` (`Cod_Curso` , `ALUMNO_Cod_Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESOR_has_ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESOR_has_ALUMNO` (
  `PROFESOR_Id_Profesor` INT NOT NULL,
  `PROFESOR_CURSO_Cod_Curso` INT NOT NULL,
  `PROFESOR_CURSO_ALUMNO_Cod_Matrícula` INT NOT NULL,
  `ALUMNO_Cod_Matrícula` INT NOT NULL,
  PRIMARY KEY (`PROFESOR_Id_Profesor`, `PROFESOR_CURSO_Cod_Curso`, `PROFESOR_CURSO_ALUMNO_Cod_Matrícula`, `ALUMNO_Cod_Matrícula`),
  INDEX `fk_PROFESOR_has_ALUMNO_ALUMNO1_idx` (`ALUMNO_Cod_Matrícula` ASC) VISIBLE,
  INDEX `fk_PROFESOR_has_ALUMNO_PROFESOR1_idx` (`PROFESOR_Id_Profesor` ASC, `PROFESOR_CURSO_Cod_Curso` ASC, `PROFESOR_CURSO_ALUMNO_Cod_Matrícula` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_has_ALUMNO_PROFESOR1`
    FOREIGN KEY (`PROFESOR_Id_Profesor` , `PROFESOR_CURSO_Cod_Curso` , `PROFESOR_CURSO_ALUMNO_Cod_Matrícula`)
    REFERENCES `mydb`.`PROFESOR` (`Id_Profesor` , `CURSO_Cod_Curso` , `CURSO_ALUMNO_Cod_Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESOR_has_ALUMNO_ALUMNO1`
    FOREIGN KEY (`ALUMNO_Cod_Matrícula`)
    REFERENCES `mydb`.`ALUMNO` (`Cod_Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
