-- MySQL Script generated by MySQL Workbench
-- Mon Oct 10 10:49:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Reservas_coche
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Reservas_coche
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Reservas_coche` DEFAULT CHARACTER SET utf8 ;
USE `Reservas_coche` ;

-- -----------------------------------------------------
-- Table `Reservas_coche`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas_coche`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(45) NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `TELÉFONO` VARCHAR(45) NULL,
  `AVALADO` TINYINT NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservas_coche`.`RESERVAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas_coche`.`RESERVAS` (
  `idRESERVAS` INT NOT NULL AUTO_INCREMENT,
  `FECHA_INICIO` DATE NULL,
  `FECHA_FINAL` DATE NULL,
  `PRECIO_TOTAL` DECIMAL(45) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `GASOLINA` INT NULL,
  PRIMARY KEY (`idRESERVAS`),
  INDEX `fk_RESERVAS_CLIENTE_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVAS_CLIENTE`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `Reservas_coche`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservas_coche`.`COCHE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas_coche`.`COCHE` (
  `idCOCHE` INT NOT NULL AUTO_INCREMENT,
  `MATRÍCULA` VARCHAR(45) NULL,
  `MODELO` INT NULL,
  `COLOR` VARCHAR(45) NULL,
  `MARCA` VARCHAR(45) NULL,
  `PRECIO_HORA` DECIMAL NULL,
  `RESERVAS_idRESERVAS` INT NOT NULL,
  PRIMARY KEY (`idCOCHE`),
  INDEX `fk_COCHE_RESERVAS1_idx` (`RESERVAS_idRESERVAS` ASC) VISIBLE,
  CONSTRAINT `fk_COCHE_RESERVAS1`
    FOREIGN KEY (`RESERVAS_idRESERVAS`)
    REFERENCES `Reservas_coche`.`RESERVAS` (`idRESERVAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
