-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 19:09:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicio2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ejercicio2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicio2` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicio2` ;

-- -----------------------------------------------------
-- Table `Ejercicio2`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2`.`PAIS` (
  `id_pAIS` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pAIS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio2`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2`.`PROVINCIA` (
  `ID_Provincia` INT NOT NULL,
  `Nombre_Provincia` VARCHAR(45) NULL,
  `PAIS_id_pAIS` INT NOT NULL,
  PRIMARY KEY (`ID_Provincia`),
  INDEX `fk_PROVINCIA_PAIS1_idx` (`PAIS_id_pAIS` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCIA_PAIS1`
    FOREIGN KEY (`PAIS_id_pAIS`)
    REFERENCES `Ejercicio2`.`PAIS` (`id_pAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio2`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2`.`LOCALIDAD` (
  `Codigo_Localidad` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Codigo_Postal` INT NULL,
  `PROVINCIA_ID_Provincia` INT NOT NULL,
  PRIMARY KEY (`Codigo_Localidad`),
  INDEX `fk_LOCALIDAD_PROVINCIA1_idx` (`PROVINCIA_ID_Provincia` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALIDAD_PROVINCIA1`
    FOREIGN KEY (`PROVINCIA_ID_Provincia`)
    REFERENCES `Ejercicio2`.`PROVINCIA` (`ID_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio2`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2`.`Empleado` (
  `Id_Empleado` INT NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Fecha_alta` DATE NULL,
  `LOCALIDAD_Codigo_Localidad` INT NOT NULL,
  PRIMARY KEY (`Id_Empleado`),
  INDEX `fk_Empleado_LOCALIDAD_idx` (`LOCALIDAD_Codigo_Localidad` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_LOCALIDAD`
    FOREIGN KEY (`LOCALIDAD_Codigo_Localidad`)
    REFERENCES `Ejercicio2`.`LOCALIDAD` (`Codigo_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
